INSERT INTO menu_items (item_name, category, price, is_available, description)
VALUES
('Chicken Nachos', 'Appetizers', 8.50, TRUE, 'Pulled chicken, white cheese sauce, cheddar, red onions, cilantro'),
('Pork Nachos', 'Appetizers', 8.50, TRUE, 'Pulled pork, white cheese sauce, pepper jack, tomato, scallions, cilantro'),
('Chicken Sliders', 'Appetizers', 5.00, TRUE, 'Three sliders with sauce choice'),
('Pork Sliders', 'Appetizers', 5.00, TRUE, 'Three sliders with sauce choice'),
('Catfish Bites', 'Appetizers', 6.50, TRUE, 'Fried catfish bites with lemon and spicy cocktail sauce'),
('Fried Veggies', 'Appetizers', 6.50, TRUE, 'Okra, zucchini, squash, or mix and match'),

('House Salad', 'Salads', 7.50, TRUE, 'Mixed greens, bacon, tomato, blue cheese'),
('Wedge Salad', 'Salads', 7.50, TRUE, 'Iceberg wedge with bacon, tomato, blue cheese'),
('Caesar Salad', 'Salads', 7.50, TRUE, 'Romaine, parmesan, croutons, Caesar dressing'),
('Sweet Potato Chicken Salad', 'Salads', 11.50, TRUE, 'Mixed greens with sweet potato crusted chicken'),

('Shrimp & Grits', 'Entrees', 13.50, TRUE, 'Sauteed shrimp over cheese grits'),
('Sweet Tea Fried Chicken', 'Entrees', 11.50, TRUE, 'Fried chicken breast with sweet tea reduction'),
('Caribbean Chicken', 'Entrees', 11.50, TRUE, 'Grilled chicken with mango salsa and avocado'),
('Grilled Pork Chops', 'Entrees', 11.00, TRUE, 'Two bone-in grilled pork chops'),
('New York Strip Steak', 'Entrees', 17.00, TRUE, 'In-house cut strip steak'),
('Seared Tuna', 'Entrees', 15.00, TRUE, 'Seared ahi tuna with mango salsa'),
('Captain Crunch Chicken Tenders', 'Entrees', 11.50, TRUE, 'Chicken tenders with dipping sauce'),
('Shock Top Grouper Fingers', 'Entrees', 11.50, TRUE, 'Beer-battered grouper with tartar sauce'),
('Mac & Cheese Bar', 'Entrees', 8.50, TRUE, 'Mac and cheese with cheese and toppings choice'),

('Curly Fries', 'Sides', 2.50, TRUE, 'Side item'),
('Wing Chips', 'Sides', 2.50, TRUE, 'Side item'),
('Sweet Potato Fries', 'Sides', 2.50, TRUE, 'Side item'),
('Creamy Cabbage Slaw', 'Sides', 2.50, TRUE, 'Side item'),
('Adluh Cheese Grits', 'Sides', 2.50, TRUE, 'Side item'),
('Mashed Potatoes', 'Sides', 2.50, TRUE, 'Side item'),
('Mac & Cheese', 'Sides', 2.50, TRUE, 'Side item'),
('Seasonal Vegetables', 'Sides', 2.50, TRUE, 'Side item'),
('Baked Beans', 'Sides', 2.50, TRUE, 'Side item'),

('Grilled Cheese', 'Sandwiches', 5.50, TRUE, 'American cheese on multigrain or white bread'),
('Chicken BLT&A', 'Sandwiches', 10.00, TRUE, 'Chicken, bacon, lettuce, tomato, avocado'),
('Philly Steak', 'Sandwiches', 13.50, TRUE, 'Shaved New York strip with vegetables and provolone'),
('Philly Chicken', 'Sandwiches', 13.50, TRUE, 'Grilled chicken with vegetables and provolone'),
('Club', 'Sandwiches', 10.00, TRUE, 'Ham, turkey, Swiss, cheddar, lettuce, tomato, mayo, bacon'),
('Meatball Sub', 'Sandwiches', 10.00, TRUE, 'House meatballs with marinara and mozzarella'),

('Bacon Cheeseburger', 'Burgers', 11.00, TRUE, 'Burger with bacon and cheese choice'),
('Carolina Burger', 'Burgers', 11.00, TRUE, 'Burger with chili, onions, slaw'),
('Portobello Burger', 'Burgers', 8.50, TRUE, 'Portobello cap with mango salsa'),
('Vegan Boca Burger', 'Burgers', 10.50, TRUE, 'Vegan Boca burger'),

('Sweet Tea', 'Beverages', 2.00, TRUE, 'Drink'),
('Unsweetened Tea', 'Beverages', 2.00, TRUE, 'Drink'),
('Coke', 'Beverages', 2.00, TRUE, 'Drink'),
('Diet Coke', 'Beverages', 2.00, TRUE, 'Drink'),
('Sprite', 'Beverages', 2.00, TRUE, 'Drink'),
('Bottled Water', 'Beverages', 2.00, TRUE, 'Drink'),
('Lemonade', 'Beverages', 2.00, TRUE, 'Drink'),
('Orange Juice', 'Beverages', 2.00, TRUE, 'Drink');